User formatting assistance and user error checking
pmcollins/opentelemetry-collector pull request #69
Opened 2021-06-25 16:13 UTC by jjackson-s

When user is given a time.Duration input field, made it so that it shows the input format the user must provide. Also some error checking for user input

Fixed bug : user input invalid values when building the overall pipelines, but not the components

Added feature kind of : Printed to console the format that we expect for time.Duration objects during component build phase

2021-06-25 18:28 UTC, pmcollins requested changes
Overall, looks good. Thanks for doing this. Will add some suggestions inline.

2021-06-25 18:32 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +
An extra line is good for visual separation. More than one consecutive line will get collapsed by a golang formatting tool (like gofmt). Does your IDE format go? If not, you can run gofmt -w . in the directory that has .go files you want to format.

2021-06-25 18:34 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +	//return "", rpe{}
Comments are often good, but commented code is usually left out of pull requests unless there's a good reason. Let's delete this line.

2021-06-25 18:37 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +
Oh sorry about that. Thanks for the tip.

2021-06-25 18:38 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +		fmt.Println("Index passed in is out of range. Try again.")
Let's reuse the same message you created above: "Invalid input. Try again." Could even make it a constant.

2021-06-25 18:42 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +		fmt.Println("Index passed in is out of range. Try again.")
Right, feel like making it a constant makes sense.

2021-06-25 18:43 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +			p.print(" (examples: 1h2m3s, 5m10s, 45s)")
For some reason this renders with 17 spaces between time.Duration and the examples. Can you look into why and see if it can be fixed?

2021-06-25 18:44 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +	return singlePipelineWizard(factories)
Recursion is an interesting approach here 😄

2021-06-25 18:49 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +			p.print(" (examples: 1h2m3s, 5m10s, 45s)")
Hmm I'm not seeing it on my end, but yes I'll look into it.

2021-06-25 18:50 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +	return singlePipelineWizard(factories)
Not sure we want the entire message to be printed again though, if just the error message makes more sense I could change it

2021-06-25 19:02 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +			p.print(" (examples: 1h2m3s, 5m10s, 45s)")
Thanks. I'm guessing it's because of the indenting printer?

2021-06-25 19:02 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +	return singlePipelineWizard(factories)
I think it's fine.

2021-06-25 23:28 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +			p.print(" (examples: 1h2m3s, 5m10s, 45s)")
Good point. Most likely so.

2021-06-28 15:57 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +			for _, processor := range r.Processors {
This processor enhancement is great, thanks for doing it. Mind putting it in a separate PR? Would prefer to keep PRs small and focused. 😄

2021-06-28 17:28 UTC, pmcollins requested changes

2021-06-28 17:28 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +const invalid string = "Invalid input. Try again."
What do you think about naming this const something like `invalidMsg`? Also, do we need the `string` part (I generally like to have less code if functionality and clarity are not affected).

2021-06-28 17:28 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +			fmt.Print(" (examples: 1h2m3s, 5m10s, 45s)")
This is fixes the problem, thanks. But for readability, is it possible to just use the indenting printer and not intermix p.print with fmt.Print?

2021-06-28 17:28 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +		if strings.Contains(name, "/") {
This functionality looks good, but can it be simpler? Can we Split in all cases, in which case we won't need to call Contains, and have a single GetCfgInfo statement?

2021-06-29 17:50 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +		if strings.Contains(name, "/") {
Works good with just single statement!

2021-06-29 17:52 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/pipelines.go
> +const invalid string = "Invalid input. Try again."
Yes more descriptive name makes sense. And was also able to take out the string part, thought that we had to type check const variables

2021-06-29 18:36 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +			fmt.Print(" (examples: 1h2m3s, 5m10s, 45s)")
Ok I think I came up with a way. Will create an output string and concatenate the values that we need. It might make sense to make a function for this in printer.go for the future if we ever need to create an example for other types.

2021-06-29 19:53 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +		cfgInfo, err := configschema.GetCfgInfo(factories, componentGroup, strings.Split(name, "/")[0])
👍

2021-06-29 19:54 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +		p.println(typString)
👍

2021-06-29 19:54 UTC, pmcollins approved these changes
LGTM, thanks!

2021-07-01 14:37 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/cli.go
> +	We are having a problem with the order in which the config file is being outputted
We should be able to just use a struct instead of a map when we want to control the order. See the `rpe` struct. We can discuss separately.

2021-07-01 14:38 UTC, merged