HandleField Test
pmcollins/opentelemetry-collector pull request #75
Opened 2021-07-01 00:53 UTC by jjackson-s

- Changed the i/o of handleField function
- Wrote a test for handleField

2021-07-01 01:04 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component_test.go
> +	}
Because the indenting printer is running the program, i cannot use fakeWriter.write() or else I would have to rework the entire code of the program

Instead I am piping stdout back to our program, and testing an expected output (expected field) on that stdout.

This is what I could come up with, but let me know your thoughts

2021-07-01 17:03 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
What do you think about leaving `clio` as it was in the example I sent over, and creating a new indentingPrinter type that accepts a `write` function? The new type could be called `indentingPrinter2` until the old one is completely replaced, then can be renamed `indentingPrinter`, or maybe the old one can be named `indentingPrinterOld` now.

2021-07-01 17:08 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
Check out the commit that I submitted after this, I think I found a way to test it without having to completely change indenting printer, but let me know your thoughts about it.

If rewriting the printer makes more sense I can go ahead and reimplement it.

2021-07-01 17:10 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
Instead of passing in the indenting printer, I was able to pass in its functions.

2021-07-01 18:27 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
So this would require that we create and pass in a new clio for each indentation level, right? I feel like it will be simpler if we have one immutable clio for the entire program.

2021-07-01 18:39 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
Oh, yes you are right. Ok I'll look into creating a new indentingPrinter that accepts a write function.

2021-07-01 18:44 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +	write indentingPrinter
BTW, just to be clear, I think the indenting printer should have the write function be a field of its struct, so when I say accepts a write function, I mean in the "constructor" 😄

2021-07-02 00:31 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	read  func(defaultVal string) string
io.write is a pointer to a func so that we can still have access to the most updated p.level where p is an instance of the indenting printer, 

Thought is that we make an indentingPrinter in the very beginning of our program, and pass in the address to ioWrite func and level to clio, which will give us the ability to write out all of our funcs and change the indentation of the printer object directly.

2021-07-02 19:30 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/printer.go
> +	write func(s string)
I was thinking it would be easier if we kept (and didn't modify) the old `indentingPrinter` and created a new `indentingPrinter2` that had the write function. Once everything is fully migrated over, then we can delete the old `indentingPrinter` (and rename the new one).

2021-07-02 19:36 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/printer.go
> +	write func(s string)
Gotcha

2021-07-02 21:36 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +	p.write = io.write
How about:
```
io := clio{printLine, readline}
p := indentingPrinter2{level: lvl, write: io.write}
```

Even better, I think, would be to create a "factory" method off of `clio` so you can just say something like:

```
p := io.newIndentingPrinter(1)
```

2021-07-02 21:47 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	p.write = io.write
I was trying to think of a way to somehow have the printer with the io struct, this makes sense though!

Also, going to create a new file for the io struct.

2021-07-02 22:02 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component.go
> +	p.write = io.write
Would it make sense to make io a constant given that it will always be declared the same in the future?

2021-07-08 17:59 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +	p.write = io.write
Technically you can't make io a constant because in Go, constants have to be character, string, boolean, or numeric values. You could make it a package `var` which is kind of like a package scoped global variable, but I don't think we want to do that -- we want to create and pass it in at runtime so we can swap the implementation.

2021-07-08 19:09 UTC, pmcollins requested changes

2021-07-08 19:09 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/printer.go
> +// Below will be removed in the future
You can just say `// Deprecated` instead and tools (like Goland 😄) will understand and highlight the function as going away.

2021-07-08 19:09 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component_test.go
> +func TestHandleField(t *testing.T) {
😎

2021-07-08 19:09 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component.go
> +func handleField(p indentingPrinter2, io clio, field *configschema.Field, out map[string]interface{}) {
nit: let's make clio the first argument since it's not like the others

2021-07-08 21:07 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/printer.go
> +// Below will be removed in the future
Really cool feature, thanks for the tip!

2021-07-08 21:34 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component_test.go
I tried to use the import formatter on Goland, but when I hit apply I did not see any changes. I mimicked the format produced by Goland and and in the other files, but may be incorrect.

2021-07-09 13:42 UTC, pmcollins commented on cmd/configschema/configwiz/configwiz/component_test.go
Did you try Code > Reformat Code?

2021-07-09 13:45 UTC, pmcollins approved these changes
LGTM, thanks!

2021-07-09 17:52 UTC, jjackson-s commented on cmd/configschema/configwiz/configwiz/component_test.go
Oh makes sense, lol thanks

2021-07-12 20:12 UTC, merged